name: Deploy 01 platform resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy-platform:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Deploy Azure resources'
      shell: pwsh
      working-directory: infrastructure
      run: ./deploy-platform.ps1
