name: Deploy environment resources

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy-development:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Deploy Azure resources'
      run: |
          az deployment sub create --location westeurope --template-file infrastructure/environment.bicep --parameters location=westeurope platformResourcePrefix=lab-msa environmentResourcePrefix=lab-msa-dev

  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy Azure resources'
      run: |
          az deployment sub create --location westeurope --template-file infrastructure/environment.bicep --parameters location=westeurope platformResourcePrefix=lab-msa environmentResourcePrefix=lab-msa-prod
