name: '2. Environments'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    strategy:
      matrix:
        environment: [ development, production ]

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:

    - name: Install latest Bicep version
      # TODO Remove this step once Bicep 0.10.13 is updated on the host runners (we need the new version for the new Bice lambda feature)
      # https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/install#linux
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep
        bicep --version

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

    - name: 'Deploy Azure resources'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Set-Location ./infrastructure
          ./deploy-environment.ps1 -Environment ${{ matrix.environment }}
        azPSVersion: "8.2.0"
