name: '2. Environments'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    strategy:
      matrix:
        environment: [ development, production ]

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

    - name: 'Deploy Azure resources'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Set-Location ./infrastructure
          ./deploy-environment.ps1 -Environment ${{ matrix.environment }}
        azPSVersion: "8.2.0"
