name: 'Deploy: 2. Environments'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy-development:
    uses: ./.github/workflows/_environment-deploy.yml
    secrets: inherit
    with:
      environment: development

  deploy-production:
    uses: ./.github/workflows/_environment-deploy.yml
    secrets: inherit
    with:
      environment: production
