name: 'Deploy: 2. Environments'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    strategy:
      matrix:
        environment: [ development, production ]
    uses: ./.github/workflows/_environment-deploy.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
