name: 'Deploy: 1. Platform'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs: 
  deploy-platform:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
  
    - name: 'Deploy Azure resources'
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Set-Location ./infrastructure
          ./deploy-platform.ps1
        azPSVersion: "latest"
