name: 'Service: _Internal/gRPC'

on:
  workflow_dispatch:
  push:
    paths:
    - services/_internal-grpc/**
    - proto/_internal-grpc.proto

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      serviceName: internal-grpc
      servicePath: services/_internal-grpc
      hostProjectName: InternalGrpc.Api

  deploy-development:
    needs: build
    uses: ./.github/workflows/_service-deploy.yml
    secrets: inherit
    with:
      service: internal-grpc
      environment: development

  # deploy-production:
  #   needs: build
  #   uses: ./.github/workflows/_service-deploy.yml
  #   secrets: inherit
  #   with:
  #     service: internal-grpc
  #     environment: production
