name: '_Internal/HTTP/Bus'

on:
  workflow_dispatch:
  push:
    paths:
    - services/_internal-http-bus/**

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/_service-build.yml
    secrets: inherit
    with:
      serviceName: internal-http-bus
      servicePath: services/_internal-http-bus
      hostProjectName: InternalHttpBus.Api

  deploy:
    strategy:
      matrix:
        # TEMPLATE_ADD_ENVIRONMENT Any new environment the service should be deployed into must be added here
        environment: [ development, production ]

    needs: build
    uses: ./.github/workflows/_service-deploy.yml
    secrets: inherit
    with:
      service: internal-http-bus
      environment: ${{ matrix.environment }}
