name: Service demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Build'
      shell: pwsh
      run: pwd


  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Deploy Azure resources'
      shell: pwsh
      working-directory: infrastructure
      run: ./deploy-service.ps1 -Service demo


  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Deploy Azure resources'
      shell: pwsh
      working-directory: infrastructure
      run: ./deploy-service.ps1 -Service demo
